title: Hello, world! I'm Thanos Tasakos
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Thanos Tasakos # add your name
author-img: profile.jpeg # add your photo
about-author: Former PH Engineer <br> Current ML Engineer  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: thanos91 # add your Github handle
social-linkedin: thanos-tasakos-09382613a # add your Linkedin handle
social-email: thanos.tas@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-spaceship
  - jekyll-toc

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
